version: 2

jobs:
  test_regression_model:
    docker:
      - image: circleci/python:3.8.0
    working_directory: ~/project
    steps:
      - checkout:
      - run:
          name: Running tests 
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/regression_model/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
            py.test -vv packages/regression_model/tests

  

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model

