#!c:\users\mohsen\desktop\myfolder\my\deployment_ml\my_ml_deploy\env\scripts\python.exe
# -*- coding: utf-8 -*-

USAGE = """Usage: echo "Héllo Wörld" | slugify # => hello-world"""

import sys
import slugify

if sys.argv[1:]:
    print >>sys.stderr, USAGE
    sys.exit(1)

line = sys.stdin.readline()
while line:
    print slugify.slugify(line.decode('utf-8'))
    line = sys.stdin.readline()
